// Generated by gencpp from file beginner_tutorials/graphicClient.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_GRAPHICCLIENT_H
#define BEGINNER_TUTORIALS_MESSAGE_GRAPHICCLIENT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/graphicClientRequest.h>
#include <beginner_tutorials/graphicClientResponse.h>


namespace beginner_tutorials
{

struct graphicClient
{

typedef graphicClientRequest Request;
typedef graphicClientResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct graphicClient
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::graphicClient > {
  static const char* value()
  {
    return "a87438d98417569022b9a6dbef5e204c";
  }

  static const char* value(const ::beginner_tutorials::graphicClient&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::graphicClient > {
  static const char* value()
  {
    return "beginner_tutorials/graphicClient";
  }

  static const char* value(const ::beginner_tutorials::graphicClient&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::graphicClientRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::graphicClient > 
template<>
struct MD5Sum< ::beginner_tutorials::graphicClientRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::graphicClient >::value();
  }
  static const char* value(const ::beginner_tutorials::graphicClientRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::graphicClientRequest> should match 
// service_traits::DataType< ::beginner_tutorials::graphicClient > 
template<>
struct DataType< ::beginner_tutorials::graphicClientRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::graphicClient >::value();
  }
  static const char* value(const ::beginner_tutorials::graphicClientRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::graphicClientResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::graphicClient > 
template<>
struct MD5Sum< ::beginner_tutorials::graphicClientResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::graphicClient >::value();
  }
  static const char* value(const ::beginner_tutorials::graphicClientResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::graphicClientResponse> should match 
// service_traits::DataType< ::beginner_tutorials::graphicClient > 
template<>
struct DataType< ::beginner_tutorials::graphicClientResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::graphicClient >::value();
  }
  static const char* value(const ::beginner_tutorials::graphicClientResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_GRAPHICCLIENT_H
