// Generated by gencpp from file beginner_tutorials/javaClientRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_JAVACLIENTREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_JAVACLIENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct javaClientRequest_
{
  typedef javaClientRequest_<ContainerAllocator> Type;

  javaClientRequest_()
    : action()
    , engineFL(0)
    , engineFR(0)
    , engineBL(0)
    , engineBR(0)
    , time(0)  {
    }
  javaClientRequest_(const ContainerAllocator& _alloc)
    : action(_alloc)
    , engineFL(0)
    , engineFR(0)
    , engineBL(0)
    , engineBR(0)
    , time(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_type;
  _action_type action;

   typedef int64_t _engineFL_type;
  _engineFL_type engineFL;

   typedef int64_t _engineFR_type;
  _engineFR_type engineFR;

   typedef int64_t _engineBL_type;
  _engineBL_type engineBL;

   typedef int64_t _engineBR_type;
  _engineBR_type engineBR;

   typedef int64_t _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> const> ConstPtr;

}; // struct javaClientRequest_

typedef ::beginner_tutorials::javaClientRequest_<std::allocator<void> > javaClientRequest;

typedef boost::shared_ptr< ::beginner_tutorials::javaClientRequest > javaClientRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::javaClientRequest const> javaClientRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::javaClientRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c173df295c85ab3371affc213cff7a8";
  }

  static const char* value(const ::beginner_tutorials::javaClientRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c173df295c85ab3ULL;
  static const uint64_t static_value2 = 0x371affc213cff7a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/javaClientRequest";
  }

  static const char* value(const ::beginner_tutorials::javaClientRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action\n\
int64 engineFL\n\
int64 engineFR\n\
int64 engineBL\n\
int64 engineBR\n\
int64 time\n\
";
  }

  static const char* value(const ::beginner_tutorials::javaClientRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.engineFL);
      stream.next(m.engineFR);
      stream.next(m.engineBL);
      stream.next(m.engineBR);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct javaClientRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::javaClientRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::javaClientRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action);
    s << indent << "engineFL: ";
    Printer<int64_t>::stream(s, indent + "  ", v.engineFL);
    s << indent << "engineFR: ";
    Printer<int64_t>::stream(s, indent + "  ", v.engineFR);
    s << indent << "engineBL: ";
    Printer<int64_t>::stream(s, indent + "  ", v.engineBL);
    s << indent << "engineBR: ";
    Printer<int64_t>::stream(s, indent + "  ", v.engineBR);
    s << indent << "time: ";
    Printer<int64_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_JAVACLIENTREQUEST_H
