// Generated by gencpp from file beginner_tutorials/javaClient.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_JAVACLIENT_H
#define BEGINNER_TUTORIALS_MESSAGE_JAVACLIENT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/javaClientRequest.h>
#include <beginner_tutorials/javaClientResponse.h>


namespace beginner_tutorials
{

struct javaClient
{

typedef javaClientRequest Request;
typedef javaClientResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct javaClient
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::javaClient > {
  static const char* value()
  {
    return "a87438d98417569022b9a6dbef5e204c";
  }

  static const char* value(const ::beginner_tutorials::javaClient&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::javaClient > {
  static const char* value()
  {
    return "beginner_tutorials/javaClient";
  }

  static const char* value(const ::beginner_tutorials::javaClient&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::javaClientRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::javaClient > 
template<>
struct MD5Sum< ::beginner_tutorials::javaClientRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::javaClient >::value();
  }
  static const char* value(const ::beginner_tutorials::javaClientRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::javaClientRequest> should match 
// service_traits::DataType< ::beginner_tutorials::javaClient > 
template<>
struct DataType< ::beginner_tutorials::javaClientRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::javaClient >::value();
  }
  static const char* value(const ::beginner_tutorials::javaClientRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::javaClientResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::javaClient > 
template<>
struct MD5Sum< ::beginner_tutorials::javaClientResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::javaClient >::value();
  }
  static const char* value(const ::beginner_tutorials::javaClientResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::javaClientResponse> should match 
// service_traits::DataType< ::beginner_tutorials::javaClient > 
template<>
struct DataType< ::beginner_tutorials::javaClientResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::javaClient >::value();
  }
  static const char* value(const ::beginner_tutorials::javaClientResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_JAVACLIENT_H
