// Generated by gencpp from file beginner_tutorials/moveCommand.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MOVECOMMAND_H
#define BEGINNER_TUTORIALS_MESSAGE_MOVECOMMAND_H

#include <ros/service_traits.h>


#include <beginner_tutorials/moveCommandRequest.h>
#include <beginner_tutorials/moveCommandResponse.h>


namespace beginner_tutorials
{

struct moveCommand
{

typedef moveCommandRequest Request;
typedef moveCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct moveCommand
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::moveCommand > {
  static const char* value()
  {
    return "79e4b5ff2a556e0eba818274612c4f67";
  }

  static const char* value(const ::beginner_tutorials::moveCommand&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::moveCommand > {
  static const char* value()
  {
    return "beginner_tutorials/moveCommand";
  }

  static const char* value(const ::beginner_tutorials::moveCommand&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::moveCommandRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::moveCommand > 
template<>
struct MD5Sum< ::beginner_tutorials::moveCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::moveCommand >::value();
  }
  static const char* value(const ::beginner_tutorials::moveCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::moveCommandRequest> should match 
// service_traits::DataType< ::beginner_tutorials::moveCommand > 
template<>
struct DataType< ::beginner_tutorials::moveCommandRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::moveCommand >::value();
  }
  static const char* value(const ::beginner_tutorials::moveCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::moveCommandResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::moveCommand > 
template<>
struct MD5Sum< ::beginner_tutorials::moveCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::moveCommand >::value();
  }
  static const char* value(const ::beginner_tutorials::moveCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::moveCommandResponse> should match 
// service_traits::DataType< ::beginner_tutorials::moveCommand > 
template<>
struct DataType< ::beginner_tutorials::moveCommandResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::moveCommand >::value();
  }
  static const char* value(const ::beginner_tutorials::moveCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MOVECOMMAND_H
