(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "JAVACLIENT"
   "<JAVACLIENT-REQUEST>"
   "JAVACLIENT-REQUEST"
   "<JAVACLIENT-RESPONSE>"
   "JAVACLIENT-RESPONSE"
   "GRAPHICCLIENT"
   "<GRAPHICCLIENT-REQUEST>"
   "GRAPHICCLIENT-REQUEST"
   "<GRAPHICCLIENT-RESPONSE>"
   "GRAPHICCLIENT-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

